[workspace]
resolver = "3"
members = [
    "crates/omni-core",
    "crates/omni-daemon",
    "crates/omni-client",
    "crates/omni-cli",
    "crates/omni-web",
]

[workspace.package]
version = "0.7.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/teamofsilicons/silicon-omni"
homepage = "https://omni.teamofsilicons.com"
readme = "README.md"

[workspace.dependencies]
omni-core = { path = "crates/omni-core", version = "0.7.0" }
silicon-omni = { path = "crates/omni-client", version = "0.7.0" }
omni-web = { path = "crates/omni-web", version = "0.7.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libc = "0.2"

[profile.release]
lto = true
codegen-units = 1
strip = true
